[project]
name = "tinawdc-rare-responses-forcer"
version = "0.1.0"
description = "Gravity Falls ARG thisisnotawebsitedotcom.com Rare Responses Forcer for those who doesn't want to refresh the webpage every time."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-webhook>=1.4.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.0",
]
